import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { GoogleMapsProvider } from "@/context/GoogleMapsContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY;
const googleMapId = process.env.GOOGLE_MAP_ID;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <GoogleMapsProvider googleMapsApiKey={googleMapsApiKey!} googleMapId={googleMapId!}>
            {children}
            <Toaster position="top-center" richColors visibleToasts={5} />
          </GoogleMapsProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
